#!/usr/bin/env python3

import argparse

import goto.globe.route

parser = argparse.ArgumentParser(description='Convert skeleton of route into a full route')

parser.add_argument('--origin', metavar='LAT/LON', type=float, nargs=2, help='coordinates of the origin')

p = parser.parse_args()

lat, lon = (0.0, 0.0) if p.origin is None else p.origin

u = goto.globe.route.RoutePrepare(lat, lon)

